# 服务器端口
server:
  port: 8081

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sssss
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志级别
logging:
  level:
    root: INFO
    com.example.mypackage: DEBUG

# 应用程序自定义属性
myapp:
  name: My Spring Boot App
  version: 1.0
